### ISSUE TITLE
Evaluation: 0.0% result

### ISSUE THREAD

**Issue by Roberto7766** [DeepAlchemist/deep-person-search#1]
Hi,
during evaluation with default values I obtain the following result:

Experiment dir: /home/roberto/PersonReID/deep-person-search/20201004/test
Loaded dataset `ssm_test` for testing
6978 roidb entries
 Backbone loading ImageNet pretrained weights from 
    ./cache/pretrained_model/resnet50_caffe.pth
Engine [baseline] was created
Not loading checkpoint!
#ModelParams : 35.05 M
extracting probe features ... 
im_exfeat: 2900/2900 0.008s   
extracting gallery features ... 
total time:1.297s, reid time:0.002s  
evaluating detections
all detection:
  recall = 0.00%
  ap = 0.00%
/home/roberto/anaconda3/envs/dps/lib/python3.6/site-packages/sklearn/metrics/ranking.py:528: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]
labeled_only detection:
  recall = 0.00%
  ap = nan%
search ranking:
  recall = 0.00%
  mAP = 0.00%
  top- 1 = 0.00%
  top- 5 = 0.00%
  top-10 = 0.00%
test time: 36.9min

The command used is:

_CUDA_VISIBLE_DEVICES=0 python main.py --is_test --benchmark ssm --eval_batch_size 5 --backbone bsl --in_level C5 --cls_type oim_

It is quite a strange result. What can be wrong?
Thanks

**Comment by deepalchemist** [comment]
Firstly, download the trained model to path_to_the_checkpoint.
Secondly,  load the checkpoint by adding --load_ckpt "absolute_path_to_your_checkpoint"  to your command.
