### ISSUE TITLE
multi gpu run

### ISSUE THREAD

**Issue by HenryZhangJianhe** [DeepAlchemist/deep-person-search#10]

**Comment by HenryZhangJianhe** [comment]
cfg setting:
parser.add_argument('--gpu_ids', type=str, default='0,1',
                            help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')

it still works in gpu 0, but not all gpus

**Comment by deepalchemist** [comment]
Hi, this code currently does not support multiple GPUs training. You can specify gpu_id via CUDA_VISIBLE_DEVICES=1 or 2 or 3.
