### ISSUE TITLE
Why freeze the weights of conv1?

### ISSUE THREAD

**Issue by ZhengPeng7** [DeepAlchemist/deep-person-search#12]
As the codes in `lib/detector/getdet.py` [ln15](https://github.com/DeepAlchemist/deep-person-search/blob/155583c08425ec3236a058b1d650212980a9c890/lib/detector/getdet.py#L15), why do you set the conv1 froze?
```
# Fix blocks
for p in self.conv1.parameters(): p.requires_grad = False
```

Thanks for your explanation.

**Comment by deepalchemist** [comment]
For fair comparison, we follow the setting of [OIM](https://openaccess.thecvf.com/content_cvpr_2017/papers/Xiao_Joint_Detection_and_CVPR_2017_paper.pdf) to freeze the params of conv1.

**Comment by ZhengPeng7** [comment]
Exactly, in section 5.1. Grazie!
