### ISSUE TITLE
About the lower performance of NAE on PRW

### ISSUE THREAD

**Issue by zhongyingji** [DeepAlchemist/deep-person-search#3]
Is there any idea on the lower performance of NAE on PRW compared with the performance reported in original paper?

**Comment by deepalchemist** [comment]
I only implement NAE model (not include NAE+), the performance of which on PRW is 43.3(mAP), and 80.9(rank1). The superior mAP (43.3 vs. 40.5) may result from 
- a larger input image size
- or testing with CWS
- or more training iterations
For more details, you can refer to the released code of NAE.

BTW, does the download link of the new Large Scale Person Search(LSPS) dataset available now?

**Comment by zhongyingji** [comment]
thanks, i get it. 
We are waiting for the approval for release. Once we are approved, we will flag it on the github page.

**Comment by deepalchemist** [comment]
OK.
