### ISSUE TITLE
Out of cpu memory

### ISSUE THREAD

**Issue by deepqd98** [DeepAlchemist/deep-person-search#4]
Hello! When I run the code, the CPU memory will keep increasing, and finally the memory will be exceeded, and the code will report an error. I tried to change the value of num_workers, but it didn't work.Do you know why this happens? What should I do?

**Comment by zsl1997** [comment]
> 你好！当我运行代码时，CPU内存将不断增加，最后将超过内存，并且代码将报告错误。我试图更改num_workers的值，但是没有用。您知道为什么会这样吗？我该怎么办？
Can you confirm whether your GPU is called? Also, does your code run through now? can I ask you some questions?

**Comment by zsl1997** [comment]
> Hello! When I run the code, the CPU memory will keep increasing, and finally the memory will be exceeded, and the code will report an error. I tried to change the value of num_workers, but it didn't work.Do you know why this happens? What should I do?
Can you confirm whether your GPU is called? Also, does your code run through now? can I ask you some questions?

**Comment by deepalchemist** [comment]
Hi, you can paste the reported error and the used launch command here.

**Comment by zsl1997** [comment]
> Hi, you can paste the reported error and the used launch command here.
First of all, in line 92 of config.py, the file does not have this run.sh,Will it matter if I delete it?
Second, below line 224 on prw.py, why relabel the id of these pedestrians? What is the use?
Third, I tested on my own data set. I modified what I said above, but an error was reported during training.
‘Nan or Inf loss occurred, ignore this batch.’,
‘File "main.py", line 43, in train_one_epoch
     _, losses = engine.optimize_parameters(cfg)
TypeError:'NoneType' object is not iterable
’
Is this a problem with my dataset or I changed the code above?

**Comment by zsl1997** [comment]
> Hi, you can paste the reported error and the used launch command here.

If you can see the message and reply to me, it would be greatly appreciated.

**Comment by zsl1997** [comment]
When I train on the original PRW dataset, the same will appear
‘File "main.py", line 43, in train_one_epoch
     _, losses = engine.optimize_parameters(cfg)
TypeError:'NoneType' object is not iterable
’
Why is that?

**Comment by deepalchemist** [comment]
> > Hi, you can paste the reported error and the used launch command here.
> > First of all, in line 92 of config.py, the file does not have this run.sh,Will it matter if I delete it?
> > Second, below line 224 on prw.py, why relabel the id of these pedestrians? What is the use?
> > Third, I tested on my own data set. I modified what I said above, but an error was reported during training.
> > ‘Nan or Inf loss occurred, ignore this batch.’,
> > ‘File "main.py", line 43, in train_one_epoch
> > _, losses = engine.optimize_parameters(cfg)
> > TypeError:'NoneType' object is not iterable
> > ’
> > Is this a problem with my dataset or I changed the code above?

1. The run.sh file originally contain the launch command, you can either create run.sh file or just delete the corresponding line 92.
2. Because the original labels are not contiguous (e.g., 1, 3, 5), but we must make it contiguous (by relabeling) for training a model.
3. As the message shows, "Nan or Inf loss occurred", you get a Nan or Inf loss. Something got wrong when training with your own data.

**Comment by deepalchemist** [comment]
> Hello! When I run the code, the CPU memory will keep increasing, and finally the memory will be exceeded, and the code will report an error. I tried to change the value of num_workers, but it didn't work.Do you know why this happens? What should I do?

Show me the report error.

**Comment by deepqd98** [comment]
Traceback (most recent call last):
  File "main.py", line 288, in <module>
    main(cfg)
  File "main.py", line 103, in main
    train_one_epoch(engine, data_loader, logger, epoch, cfg.warmup_epochs)
  File "main.py", line 33, in train_one_epoch
    for idx, data in enumerate(data_loader):
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Training program can run. But, during the training process, the memory usage keeps increasing and finally exceeds the memory. Although my workstation has 256G of memory, it still exceeds the memory limit. By the way , the batch size is 5 and GPU is rtx2080ti. It didn't  exceed GPU memory.

**Comment by zsl1997** [comment]
Maybe you change n_work to 8 or 4 to try




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deepqd98"<notifications@github.com&gt;; 
发送时间: 2020年11月3日(星期二) 下午3:57
收件人: "DeepAlchemist/deep-person-search"<deep-person-search@noreply.github.com&gt;; 
抄送: "赵石磊"<649162208@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [DeepAlchemist/deep-person-search] Out of cpu memory (#4)





 
Traceback (most recent call last):
 File "main.py", line 288, in 
 main(cfg)
 File "main.py", line 103, in main
 train_one_epoch(engine, data_loader, logger, epoch, cfg.warmup_epochs)
 File "main.py", line 33, in train_one_epoch
 for idx, data in enumerate(data_loader):
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in iter
 return _MultiProcessingDataLoaderIter(self)
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 682, in init
 w.start()
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/process.py", line 105, in start
 self._popen = self._Popen(self)
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
 return _default_context.get_context().Process._Popen(process_obj)
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
 return Popen(process_obj)
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/popen_fork.py", line 19, in init
 self._launch(process_obj)
 File "/home/tongji/miniconda3/envs/dps/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
 self.pid = os.fork()
 OSError: [Errno 12] Cannot allocate memory
 
Training program can run. But, during the training process, the memory usage keeps increasing and finally exceeds the memory. Although my workstation has 256G of memory, it still exceeds the memory limit. By the way , the batch size is 5 and GPU is rtx2080ti. It didn't  exceed GPU memory.

**Comment by deepqd98** [comment]
I changed n_worker to 8, 4, 2, 0, but it doesn’t work. Have you ever encountered this problem when running the training program?

**Comment by zsl1997** [comment]
I haven't had this problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deepqd98"<notifications@github.com&gt;; 
发送时间: 2020年11月3日(星期二) 晚上9:05
收件人: "DeepAlchemist/deep-person-search"<deep-person-search@noreply.github.com&gt;; 
抄送: "赵石磊"<649162208@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [DeepAlchemist/deep-person-search] Out of cpu memory (#4)





 
I changed n_worker to 8, 4, 2, 0, but it doesn’t work. Have you ever encountered this problem when running the training program?

**Comment by HenryZhangJianhe** [comment]
I have the same issue as you: out of cpu memery.
Did you fix this issue?

**Comment by zsl1997** [comment]
Try decreasing the numwork and decreasing the batchsize.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DeepAlchemist/deep-person-search"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 凌晨0:45
收件人:&nbsp;"DeepAlchemist/deep-person-search"<deep-person-search@noreply.github.com&gt;;
抄送:&nbsp;"赵石磊"<649162208@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DeepAlchemist/deep-person-search] Out of cpu memory (#4)





 
I have the same issue as you: out of cpu memery.
 Did you fix this issue?

**Comment by HenryZhangJianhe** [comment]
It will work after changing TwoStage.py as follows:
![image](https://user-images.githubusercontent.com/52202915/101727756-12fc0380-3af0-11eb-8d95-45ba98e450d3.png)

**Comment by green-615** [comment]
> It will work after changing TwoStage.py as follows:
> ![image](https://user-images.githubusercontent.com/52202915/101727756-12fc0380-3af0-11eb-8d95-45ba98e450d3.png)



> It will work after changing TwoStage.py as follows:
> ![image](https://user-images.githubusercontent.com/52202915/101727756-12fc0380-3af0-11eb-8d95-45ba98e450d3.png)

hi ，i have tried your method but it doesn't work，do you change other code？or your pytorch version ? 
i have met AttributeError 'float' object has no attribute 'item'
