### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by zsl1997** [DeepAlchemist/deep-person-search#5]
When I train on the original PRW dataset, the same will appear
‘File "main.py", line 43, in train_one_epoch
_, losses = engine.optimize_parameters(cfg)
TypeError:'NoneType' object is not iterable
’
Why is that?
Looking forward to your reply

**Comment by deepalchemist** [comment]
Hi, please paste the launch command that you use.

**Comment by zsl1997** [comment]
> Hi, please paste the launch command that you use.

CUDA_VISIBLE_DEVICES=0 python main.py --benchmark prw --batch_size 2 --backbone bsl --in_level C5 --cls_type oim --lr 0.0005 --warmup_epochs 1 --max_epoch 7 --suffix "" --div

**Comment by deepalchemist** [comment]
> > Hi, please paste the launch command that you use.
> 
> CUDA_VISIBLE_DEVICES=0 python main.py --benchmark prw --batch_size 2 --backbone bsl --in_level C5 --cls_type oim --lr 0.0005 --warmup_epochs 1 --max_epoch 7 --suffix "" --div

Please remove --div.

**Comment by zsl1997** [comment]
> > > Hi, please paste the launch command that you use.
> > 
> > 
> > CUDA_VISIBLE_DEVICES=0 python main.py --benchmark prw --batch_size 2 --backbone bsl --in_level C5 --cls_type oim --lr 0.0005 --warmup_epochs 1 --max_epoch 7 --suffix "" --div
> 
> Please remove --div.

OK   Thank you so much

**Comment by ZhengPeng7** [comment]
Could you explain why remove the --div help solve this?
I also met this problem. After debugging, I found that **_the features (C2 / C3 / C4) from the backbone could be **inf** or **nan**_**. That caused `optimize_parameters` to return None, which is not iterable.

Codes ran very well on PRW and SSM, but when I trained on my own dataset, the features turned nan from time to time.
Your codes are very comprehensive and have the grad clip to avoid nan/inf, but I don't really want to turn it on.
I checked the exact array just one step before the backbone, they looked very normal.

Do you have any solution to it? Thanks a lot!

P.S. my train.sh:
```
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main.py \
    --benchmark mvn --batch_size 2 \
    --backbone bsl --in_level C5 --cls_type oim \
    --lr 0.003 --warmup_epochs 1 --max_epoch 25
```
