### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by zsl1997** [DeepAlchemist/deep-person-search#7]
Excuse me, in this code, the unrecognizable id is set to -1, and then these pictures are deleted during training. I found that during training, all the remaining frames (training and testing frames) are trained instead of The remaining frames in the training set. Why is that?

**Comment by deepalchemist** [comment]
I do not get your point. Do you mean the models are trained on the combined set of the training split and test split?

**Comment by zsl1997** [comment]
Sorry, I didn't make it clear before. The problem I encountered was that after training on my own dataset, the test index was very low. I have a guess that there are some test pedestrian ids in my training frames. I marked these ids as -1, and then filtered out many training frames, resulting in poor results. That is, there is a problem with my dataset. Is it possible?

**Comment by deepalchemist** [comment]
Yes, you should make sure the test identities are not seen in the training stage. As for the unsatisfying performances on your own datasets, forgive me I have not idea about this.
